on:
  push:
    branches:
      - master
      - test

jobs:
  test_job:
    name: "Test Job"
    runs-on: ubuntu-latest
    steps:
      - name: Branch switch
        shell: bash
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/};
          if BRANCH_NAME = "master" ; then
            DIR_NAME="This is master!"
          else
            DIR_NAME="This is test!"
          fi
          echo "${DIR_NAME}"
